const { getBuffer, commandArgument, formatError } = require('../lib/tkmApi');

async function imagineCommand(sock, chatId, message) {
    const prompt = commandArgument(message);
    if (!prompt) return sock.sendMessage(chatId, { text: 'Usage: .imagine <prompt>' }, { quoted: message });
    try {
        await sock.sendMessage(chatId, { text: 'T is generating your image...' }, { quoted: message });
        const { buffer } = await getBuffer('/ai/FluxLora', { prompt, width: 1024, height: 1024 });
        await sock.sendMessage(chatId, { image: buffer, caption: `Generated by T\n\n${prompt}` }, { quoted: message });
    } catch (error) {
        console.error('[IMAGINE] command error:', error);
        await sock.sendMessage(chatId, { text: formatError(error) }, { quoted: message });
    }
}
module.exports = imagineCommand;
